### ISSUE TITLE
测距后点击消除有部分未清掉

### ISSUE THREAD

**Issue by mjj-jinqiang** [qin9smile/mapboxgl-measure-control#1]
#

**Comment by singlebibi** [comment]
这个bug您解决了吗?

**Comment by linksee-dev** [comment]
Duplicate of #3 #2

**Comment by linksee-dev** [comment]
> 这个bug您解决了吗?

现在解决啦

**Comment by singlebibi** [comment]
首先，谢谢您对这个问题能进行解决。其次，刚才在测试的时候发现，点击X,重新进行测距时候就会出错。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "qin9smile/mapboxgl-measure-control"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月16日(星期三) 下午4:13
收件人:&nbsp;"qin9smile/mapboxgl-measure-control"<mapboxgl-measure-control@noreply.github.com&gt;;
抄送:&nbsp;"装备1101  刘栋"<985032913@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [qin9smile/mapboxgl-measure-control] 测距后点击消除有部分未清掉 (#1)





 
Duplicate of #3 #2

**Comment by linksee-dev** [comment]
@singlebibi  已经修复啦 https://github.com/qin9smile/mapboxgl-measure-control/commit/5ddb2047356841641b9d8c06d8aa2b08fd35b17c
